alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: itsandy-flask-hola
    match:
      path:
        prefix: /
name: clownfish-app
region: sfo
services:
- http_port: 8080
  image:
    registry: itsandy
    registry_type: DOCKER_HUB
    repository: flask-hola
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: itsandy-flask-hola
