name: clownfish-app
region: sfo
services:
  - name: itsandy-flask-hola
    github:
      repo: AndyChiquin/python_project  # Usa tu usuario y repo reales
      branch: main
      deploy_on_push: true
    run_command: python app.py
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs: []
