name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t itsandy/flask-hola:latest .
        docker push itsandy/flask-hola:latest

    - name: Install doctl
      run: |
        sudo snap install doctl --classic

    - name: Authenticate with DigitalOcean
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      run: doctl auth init -t $DIGITALOCEAN_TOKEN

    - name: Deploy to DigitalOcean
      run: doctl apps update --spec .do/app.yaml
