name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install doctl
      run: sudo snap install doctl --classic

    - name: Authenticate with DigitalOcean
      env:
        DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      run: doctl auth init -t $DIGITALOCEAN_TOKEN

    - name: Deploy to DigitalOcean App Platform
      run: doctl apps update 3c9a211c-40ad-4281-a13e-c0657e0ac140 --spec .do/app.yaml
